// <auto-generated />
using System;
using EvidenceProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Migrations.Postgres.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20230102162154_PostgresMigration2")]
    partial class PostgresMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DialCodeProject", b =>
                {
                    b.Property<int>("Technology")
                        .HasColumnType("integer");

                    b.Property<int>("projectTechnologyid")
                        .HasColumnType("integer");

                    b.HasKey("Technology", "projectTechnologyid");

                    b.HasIndex("projectTechnologyid");

                    b.ToTable("DialCodeProject");
                });

            modelBuilder.Entity("EvidenceProject.Data.DataModels.Achievement", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<int>("projectid")
                        .HasColumnType("integer");

                    b.HasKey("name");

                    b.HasIndex("projectid");

                    b.ToTable("Achievement");
                });

            modelBuilder.Entity("EvidenceProject.Data.DataModels.DbFile", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Projectid")
                        .HasColumnType("integer");

                    b.Property<byte[]>("fileData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("generatedFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("originalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Projectid");

                    b.ToTable("files");
                });

            modelBuilder.Entity("EvidenceProject.Data.DataModels.DialCode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Technology")
                        .HasColumnType("integer");

                    b.Property<int>("_color")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("dialInfoid")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("dialInfoid");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("dialCodes");
                });

            modelBuilder.Entity("EvidenceProject.Data.DataModels.DialInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("desc")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("dialInfos");
                });

            modelBuilder.Entity("EvidenceProject.Data.DataModels.Project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("AuthUser")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("github")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("projectDescription")
                        .HasColumnType("text");

                    b.Property<string>("slack")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("AuthUser");

                    b.HasIndex("State");

                    b.HasIndex("Type");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("EvidenceProject.Data.DataModels.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Applicants")
                        .HasColumnType("integer");

                    b.Property<int?>("Assigness")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("contactDetails")
                        .HasColumnType("text");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte?>("schoolYear")
                        .HasColumnType("smallint");

                    b.Property<string>("studyField")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjectUser", b =>
                {
                    b.Property<int>("Assigness")
                        .HasColumnType("integer");

                    b.Property<int>("assigneesid")
                        .HasColumnType("integer");

                    b.HasKey("Assigness", "assigneesid");

                    b.HasIndex("assigneesid");

                    b.ToTable("ProjectUser");
                });

            modelBuilder.Entity("ProjectUser1", b =>
                {
                    b.Property<int>("Applicants")
                        .HasColumnType("integer");

                    b.Property<int>("applicantsid")
                        .HasColumnType("integer");

                    b.HasKey("Applicants", "applicantsid");

                    b.HasIndex("applicantsid");

                    b.ToTable("ProjectUser1");
                });

            modelBuilder.Entity("EvidenceProject.Data.DataModels.AuthUser", b =>
                {
                    b.HasBaseType("EvidenceProject.Data.DataModels.User");

                    b.Property<bool?>("globalAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("id_key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("id_key")
                        .IsUnique();

                    b.HasIndex("username")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("AuthUser");
                });

            modelBuilder.Entity("DialCodeProject", b =>
                {
                    b.HasOne("EvidenceProject.Data.DataModels.Project", null)
                        .WithMany()
                        .HasForeignKey("Technology")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvidenceProject.Data.DataModels.DialCode", null)
                        .WithMany()
                        .HasForeignKey("projectTechnologyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvidenceProject.Data.DataModels.Achievement", b =>
                {
                    b.HasOne("EvidenceProject.Data.DataModels.Project", "project")
                        .WithMany("projectAchievements")
                        .HasForeignKey("projectid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("project");
                });

            modelBuilder.Entity("EvidenceProject.Data.DataModels.DbFile", b =>
                {
                    b.HasOne("EvidenceProject.Data.DataModels.Project", null)
                        .WithMany("files")
                        .HasForeignKey("Projectid");
                });

            modelBuilder.Entity("EvidenceProject.Data.DataModels.DialCode", b =>
                {
                    b.HasOne("EvidenceProject.Data.DataModels.DialInfo", "dialInfo")
                        .WithMany("dialCodes")
                        .HasForeignKey("dialInfoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dialInfo");
                });

            modelBuilder.Entity("EvidenceProject.Data.DataModels.Project", b =>
                {
                    b.HasOne("EvidenceProject.Data.DataModels.AuthUser", "projectManager")
                        .WithMany()
                        .HasForeignKey("AuthUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidenceProject.Data.DataModels.DialCode", "projectState")
                        .WithMany()
                        .HasForeignKey("State")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvidenceProject.Data.DataModels.DialCode", "projectType")
                        .WithMany()
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("projectManager");

                    b.Navigation("projectState");

                    b.Navigation("projectType");
                });

            modelBuilder.Entity("ProjectUser", b =>
                {
                    b.HasOne("EvidenceProject.Data.DataModels.Project", null)
                        .WithMany()
                        .HasForeignKey("Assigness")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvidenceProject.Data.DataModels.User", null)
                        .WithMany()
                        .HasForeignKey("assigneesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectUser1", b =>
                {
                    b.HasOne("EvidenceProject.Data.DataModels.Project", null)
                        .WithMany()
                        .HasForeignKey("Applicants")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvidenceProject.Data.DataModels.User", null)
                        .WithMany()
                        .HasForeignKey("applicantsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvidenceProject.Data.DataModels.DialInfo", b =>
                {
                    b.Navigation("dialCodes");
                });

            modelBuilder.Entity("EvidenceProject.Data.DataModels.Project", b =>
                {
                    b.Navigation("files");

                    b.Navigation("projectAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
